### ISSUE TITLE
Question on ng-repeat

### ISSUE THREAD

**Issue by petreboy14** [gethuman/jangular#2]
Hey just wondering if you've been able to figure out how to handle server side rendering of ng-repeat with the client side being able to bootstrap correctly. I've been trying to figure out how to do this and most of the time either get no results or duplicated ones. Taking the sample todo app as an example, if this is in my template:
```
<div class='checkbox' ng-repeat='todo in todos'>
    <label>
        <input type='checkbox' ng-click='deleteTodo(todo._id)' ng-bind='todo.text'>
    </label>
</div>
```
and this is my data: 
`var todos = [{ _id: 0, text: 'foo-1' }, { _id: 1, text: 'foo-2' }];`

when it renders without any type of client side loading of the data I will get:
```
<div class="checkbox" ng-repeat="todo in todos">
     <label>
          <input type="checkbox" ng-click="deleteTodo(todo._id)" ng-bind="todo.text">foo-1</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
    <label>
        <input type="checkbox" ng-click="deleteTodo(todo._id)" ng-bind="todo.text">foo-2</input>
    </label>
</div>
```
which will disappear as soon as angular figures out that $scope.todos is null or empty.

If i try to include client side loading with some kind of query to get the todos array from the server I'll end up with something like this with repeated elements:

```
<div class="checkbox" ng-repeat="todo in todos">
     <label>
          <input type="checkbox" ng-click="deleteTodo(todo._id)" ng-bind="todo.text">foo-1</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
    <label>
        <input type="checkbox" ng-click="deleteTodo(todo._id)" ng-bind="todo.text">foo-2</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
     <label>
          <input type="checkbox" ng-click="deleteTodo(todo._id)" ng-bind="todo.text">foo-1</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
    <label>
        <input type="checkbox" ng-click="deleteTodo(todo._id)" ng-bind="todo.text">foo-2</input>
    </label>
</div>
```
I'm assuming this is because angular is seeing two blocks of ng-repeats and so is filling both blocks with the values for $scope.todos.

Of course, removing the ng-repeat tags will allow the values to show up correctly but then there is no watch expression on $scope.todos and I'm not quite sure how to set a ng-repeat directive on the existing list programmatically.

So question is have you found a way to server side render repeated blocks and set the scoped collection correctly from the client side without a bunch of repeats? Thanks for any guidance :-)

**Comment by christianallen** [comment]
Hi, Peter. Thanks for the great question. We struggled with this exactly
problem for some time before we finally gave up trying to "re-bind" client
side Angular on top of the server side generated page. Our solution for
this instead is to "re-render" by using the ui-router (or angular router).
Basically the way it would work is as follows:

1. Have a ui-view near the top of your HTML template:

<body ng-app="myApp"><ui-view>etc.

2. When you run the template through Jangular, use the strip: true option
which will remove all angular template code within ui-view, but not the
ui-view
3. Let Angular on the client side render the page through the view. This
will completely re-render the page, but it should be seemless if you set it
up right.

Let me know if you run into any issues. Also, as an FYI, this particular
problem will be solved with the Angular2 version that we are working on
now. Angular2 knows how to properly "re-bind" so there will be no need for
the ui-view or re-rendering.

Jeff


---------- Forwarded message ----------
From: Christian Allen <christian@christianallen.com>
Date: Tue, Mar 17, 2015 at 7:32 AM
Subject: Fwd: [jangular] Question on ng-repeat (#2)
To: Jeff Whelpley <jeff@gethuman.com>


Wow- our first really good question (!)


Begin forwarded message:

*From:* Peter Henning <notifications@github.com>
*Date:* March 17, 2015 at 2:59:55 AM EDT
*To:* gethuman/jangular <jangular@noreply.github.com>
*Subject:* *[jangular] Question on ng-repeat (#2)*
*Reply-To:* gethuman/jangular <
reply@reply.github.com
>

Hey just wondering if you've been able to figure out how to handle server
side rendering of ng-repeat with the client side being able to bootstrap
correctly. I've been trying to figure out how to do this and most of the
time either get no results or duplicated ones. Taking the sample todo app
as an example, if this is in my template:

<div class='checkbox' ng-repeat='todo in todos'>
    <label>
        <input type='checkbox' ng-click='deleteTodo(todo._id)'
ng-bind='todo.text'>
    </label>
</div>

and this is my data:
var todos = [{ _id: 0, text: 'foo-1' }, { _id: 1, text: 'foo-2' }];

when it renders without any type of client side loading of the data I will
get:

<div class="checkbox" ng-repeat="todo in todos">
     <label>
          <input type="checkbox" ng-click="deleteTodo(todo._id)"
ng-bind="todo.text">foo-1</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
    <label>
        <input type="checkbox" ng-click="deleteTodo(todo._id)"
ng-bind="todo.text">foo-2</input>
    </label>
</div>

which will disappear as soon as angular figures out that $scope.todos is
null or empty.

If i try to include client side loading with some kind of query to get the
todos array from the server I'll end up with something like this with
repeated elements:

<div class="checkbox" ng-repeat="todo in todos">
     <label>
          <input type="checkbox" ng-click="deleteTodo(todo._id)"
ng-bind="todo.text">foo-1</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
    <label>
        <input type="checkbox" ng-click="deleteTodo(todo._id)"
ng-bind="todo.text">foo-2</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
     <label>
          <input type="checkbox" ng-click="deleteTodo(todo._id)"
ng-bind="todo.text">foo-1</input>
    </label>
</div>
<div class="checkbox" ng-repeat="todo in todos">
    <label>
        <input type="checkbox" ng-click="deleteTodo(todo._id)"
ng-bind="todo.text">foo-2</input>
    </label>
</div>

I'm assuming this is because angular is seeing two blocks of ng-repeats and
so is filling both blocks with the values for $scope.todos.

Of course, removing the ng-repeat tags will allow the values to show up
correctly but then there is no watch expression on $scope.todos and I'm not
quite sure how to set a ng-repeat directive on the existing list
programmatically.

So question is have you found a way to server side render repeated blocks
and set the scoped collection correctly from the client side without a
bunch of repeats? Thanks for any guidance :-)

—
Reply to this email directly or view it on GitHub
<https://github.com/gethuman/jangular/issues/2>.

**Comment by jeffwhelpley** [comment]
I am going to close this issue, but @petreboy14 please note that I am in the middle of working with the Angular core team on server rendering in Angular 2 and we will have a much more elegant solution there than the re-render solution that is used with Jangular.
